// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrN-c4-IyOX-wULj664MoLuxh9wraWOC4',
    appId: '1:637170339416:web:aca73e19f16645ed49842d',
    messagingSenderId: '637170339416',
    projectId: 'chatingapp-2ea19',
    authDomain: 'chatingapp-2ea19.firebaseapp.com',
    storageBucket: 'chatingapp-2ea19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIiY-LUOCfQs--Xy-ZqTgcF4ZH7mouOpg',
    appId: '1:637170339416:android:48ec702383c712f249842d',
    messagingSenderId: '637170339416',
    projectId: 'chatingapp-2ea19',
    storageBucket: 'chatingapp-2ea19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiJluCQSbFI_Jgc-tlY13E5eCNKu11Lbg',
    appId: '1:637170339416:ios:7667b9b0a56b953949842d',
    messagingSenderId: '637170339416',
    projectId: 'chatingapp-2ea19',
    storageBucket: 'chatingapp-2ea19.firebasestorage.app',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiJluCQSbFI_Jgc-tlY13E5eCNKu11Lbg',
    appId: '1:637170339416:ios:7667b9b0a56b953949842d',
    messagingSenderId: '637170339416',
    projectId: 'chatingapp-2ea19',
    storageBucket: 'chatingapp-2ea19.firebasestorage.app',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrN-c4-IyOX-wULj664MoLuxh9wraWOC4',
    appId: '1:637170339416:web:084db4379d9b6f4649842d',
    messagingSenderId: '637170339416',
    projectId: 'chatingapp-2ea19',
    authDomain: 'chatingapp-2ea19.firebaseapp.com',
    storageBucket: 'chatingapp-2ea19.firebasestorage.app',
  );
}
